"""
ROIF directed capacity model.

This module implements the directional effective capacity

    κ_i(d, x) = c_i · α_i · <d, a_i(x)>_+

where:

    c_i      — structural capacity of element i;
    α_i      — current availability, 0 <= α_i <= 1;
    d        — normalized load direction;
    a_i(x)   — element service direction in configuration x;
    <.,.>_+  — positive-part directional projection.

The module also supports:

- tension-only, compression-only and bidirectional elements;
- anisotropic directional weighting;
- configuration-dependent element orientation;
- active and passive element classification;
- safe validation of vectors and matrices.

The mechanical core should not depend on this module.
The ROIF layer may use objects from core, but κ remains a separate
analytical representation of functional capacity.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Iterable, TypeAlias

import numpy as np
from numpy.typing import NDArray


FloatArray: TypeAlias = NDArray[np.float64]

_EPSILON = 1e-12


class CapacityTensorError(ValueError):
    """Raised when a directed-capacity model receives invalid data."""


class ResponseMode(str, Enum):
    """
    Mechanical direction in which an element can serve load.

    TENSION:
        The element serves load only when d points along its axis.

    COMPRESSION:
        The element serves load only when d points against its axis.

    BIDIRECTIONAL:
        The element serves both signs of axial load.
    """

    TENSION = "tension"
    COMPRESSION = "compression"
    BIDIRECTIONAL = "bidirectional"


class ElementActivity(str, Enum):
    """
    Functional classification of an element.

    PASSIVE:
        Capacity is determined by structure and current availability.

    ACTIVE:
        Capacity can additionally be modulated by activation.
    """

    PASSIVE = "passive"
    ACTIVE = "active"


@dataclass(frozen=True, slots=True)
class CapacityEvaluation:
    """
    Detailed result of one κ(d, x) evaluation.

    Attributes
    ----------
    effective_capacity:
        Final directed capacity κ(d, x).

    base_capacity:
        Structural capacity c.

    availability:
        Availability coefficient α.

    activation:
        Active control coefficient. It equals 1 for passive elements.

    projection:
        Signed scalar projection before response-mode clipping.

    usable_projection:
        Projection after applying tension/compression/bidirectional rules.

    anisotropic_weight:
        Directional weighting generated by the anisotropy matrix.

    direction:
        Normalized external load direction d.

    service_axis:
        Normalized configured element axis a(x).
    """

    effective_capacity: float
    base_capacity: float
    availability: float
    activation: float
    projection: float
    usable_projection: float
    anisotropic_weight: float
    direction: FloatArray
    service_axis: FloatArray

    @property
    def utilization_denominator(self) -> float:
        """
        Capacity value that may be used as the denominator in u = T / κ.

        A zero value is preserved. The fast or slow layer must explicitly
        decide how unavailable directions are handled.
        """

        return self.effective_capacity


@dataclass(slots=True)
class CapacityTensor:
    """
    Direction-dependent capacity of one ROIF element.

    The minimal article-consistent case is obtained with:

        anisotropy = identity matrix
        response_mode = TENSION
        activity = PASSIVE
        activation = 1

    which gives:

        κ(d, x) = c · α · max(0, <d, a(x)>)

    Parameters
    ----------
    base_capacity:
        Structural capacity c. Must be finite and non-negative.

    availability:
        Functional availability α in [0, 1].

    local_axis:
        Preferred element direction in its local/reference configuration.

    anisotropy:
        Optional symmetric positive-semidefinite matrix describing
        additional directional weighting. Identity is used by default.

    response_mode:
        Whether the element serves tension, compression, or both.

    activity:
        Active or passive element classification.

    activation:
        Current activation coefficient in [0, 1]. It affects only active
        elements. Passive elements always use activation = 1.

    element_id:
        Optional identifier used by localization and intervention layers.
    """

    base_capacity: float
    availability: float
    local_axis: Iterable[float] | FloatArray

    anisotropy: Iterable[Iterable[float]] | FloatArray | None = None
    response_mode: ResponseMode = ResponseMode.TENSION
    activity: ElementActivity = ElementActivity.PASSIVE
    activation: float = 1.0
    element_id: str | int | None = None

    _axis: FloatArray = field(init=False, repr=False)
    _anisotropy: FloatArray = field(init=False, repr=False)

    def __post_init__(self) -> None:
        self.base_capacity = self._validate_non_negative_scalar(
            self.base_capacity,
            name="base_capacity",
        )
        self.availability = self._validate_unit_interval(
            self.availability,
            name="availability",
        )
        self.activation = self._validate_unit_interval(
            self.activation,
            name="activation",
        )

        self.response_mode = ResponseMode(self.response_mode)
        self.activity = ElementActivity(self.activity)

        self._axis = self._normalize_vector(
            self.local_axis,
            name="local_axis",
        )

        dimension = self._axis.size

        if self.anisotropy is None:
            self._anisotropy = np.eye(dimension, dtype=np.float64)
        else:
            self._anisotropy = self._validate_anisotropy_matrix(
                self.anisotropy,
                dimension=dimension,
            )

    @property
    def dimension(self) -> int:
        """Spatial dimension of the capacity model."""

        return int(self._axis.size)

    @property
    def axis(self) -> FloatArray:
        """Return a defensive copy of the normalized local axis."""

        return self._axis.copy()

    @property
    def anisotropy_matrix(self) -> FloatArray:
        """Return a defensive copy of the anisotropy matrix."""

        return self._anisotropy.copy()

    @property
    def effective_activation(self) -> float:
        """
        Return activation used in κ.

        Passive elements are not reduced by the active-control coefficient.
        """

        if self.activity is ElementActivity.ACTIVE:
            return self.activation

        return 1.0

    @property
    def available_capacity(self) -> float:
        """
        Capacity after availability and active-control modulation.

        This is c · α for passive elements and c · α · β for active ones.
        Directional geometry is not included.
        """

        return (
            self.base_capacity
            * self.availability
            * self.effective_activation
        )

    def configured_axis(
        self,
        configuration: Iterable[Iterable[float]] | FloatArray | None = None,
    ) -> FloatArray:
        """
        Calculate a(x), the element axis in configuration x.

        Parameters
        ----------
        configuration:
            Rotation or orientation matrix with shape (n, n). When omitted,
            the local/reference axis is used unchanged.

        Returns
        -------
        numpy.ndarray
            Normalized configured service axis.

        Notes
        -----
        The matrix is treated as an orientation transformation:

            a(x) = normalize(R(x) @ a_local)

        Strict orthogonality is not required here because some numerical
        solvers produce slightly non-orthogonal matrices. The resulting axis
        is normalized after transformation.
        """

        if configuration is None:
            return self._axis.copy()

        matrix = np.asarray(configuration, dtype=np.float64)

        expected_shape = (self.dimension, self.dimension)
        if matrix.shape != expected_shape:
            raise CapacityTensorError(
                "configuration must have shape "
                f"{expected_shape}, received {matrix.shape}."
            )

        if not np.all(np.isfinite(matrix)):
            raise CapacityTensorError(
                "configuration contains non-finite values."
            )

        configured = matrix @ self._axis

        return self._normalize_vector(
            configured,
            name="configured_axis",
        )

    def projection(
        self,
        direction: Iterable[float] | FloatArray,
        configuration: Iterable[Iterable[float]] | FloatArray | None = None,
    ) -> float:
        """
        Calculate the signed projection <d, a(x)>.

        Both vectors are normalized before the dot product.
        """

        normalized_direction = self._normalize_vector(
            direction,
            name="direction",
            expected_dimension=self.dimension,
        )
        axis = self.configured_axis(configuration)

        return float(np.dot(normalized_direction, axis))

    def usable_projection(self, signed_projection: float) -> float:
        """
        Apply the element's unilateral or bilateral response rule.

        For tension-only elements:

            p = max(0, <d, a>)

        For compression-only elements:

            p = max(0, -<d, a>)

        For bidirectional elements:

            p = abs(<d, a>)
        """

        value = float(signed_projection)

        if not np.isfinite(value):
            raise CapacityTensorError(
                "signed_projection must be finite."
            )

        if self.response_mode is ResponseMode.TENSION:
            return max(0.0, value)

        if self.response_mode is ResponseMode.COMPRESSION:
            return max(0.0, -value)

        return abs(value)

    def anisotropic_weight(
        self,
        direction: Iterable[float] | FloatArray,
    ) -> float:
        """
        Calculate non-negative anisotropic weighting for direction d.

        The normalized quadratic form is used:

            w_A(d) = sqrt(dᵀ A d)

        Identity anisotropy gives w_A(d) = 1 for every normalized direction.

        This weight extends the basic article equation without changing its
        minimal isotropic form.
        """

        normalized_direction = self._normalize_vector(
            direction,
            name="direction",
            expected_dimension=self.dimension,
        )

        quadratic_form = float(
            normalized_direction
            @ self._anisotropy
            @ normalized_direction
        )

        # Small negative values can appear because of floating-point error.
        if quadratic_form < -_EPSILON:
            raise CapacityTensorError(
                "anisotropy produced a negative quadratic form."
            )

        return float(np.sqrt(max(0.0, quadratic_form)))

    def evaluate(
        self,
        direction: Iterable[float] | FloatArray,
        configuration: Iterable[Iterable[float]] | FloatArray | None = None,
    ) -> CapacityEvaluation:
        """
        Fully evaluate κ(d, x) and return its components.

        The generalized expression is:

            κ(d, x)
                = c
                · α
                · β
                · response(<d, a(x)>)
                · sqrt(dᵀ A d)

        where β is active activation and equals 1 for passive elements.

        With identity anisotropy and a passive tension-only element this
        reduces exactly to:

            κ(d, x) = c · α · <d, a(x)>_+
        """

        normalized_direction = self._normalize_vector(
            direction,
            name="direction",
            expected_dimension=self.dimension,
        )
        axis = self.configured_axis(configuration)

        signed_projection = float(
            np.dot(normalized_direction, axis)
        )
        service_projection = self.usable_projection(
            signed_projection
        )
        directional_weight = self.anisotropic_weight(
            normalized_direction
        )

        capacity = (
            self.base_capacity
            * self.availability
            * self.effective_activation
            * service_projection
            * directional_weight
        )

        # Prevent insignificant negative values due to floating-point error.
        capacity = max(0.0, float(capacity))

        return CapacityEvaluation(
            effective_capacity=capacity,
            base_capacity=self.base_capacity,
            availability=self.availability,
            activation=self.effective_activation,
            projection=signed_projection,
            usable_projection=service_projection,
            anisotropic_weight=directional_weight,
            direction=normalized_direction.copy(),
            service_axis=axis.copy(),
        )

    def kappa(
        self,
        direction: Iterable[float] | FloatArray,
        configuration: Iterable[Iterable[float]] | FloatArray | None = None,
    ) -> float:
        """
        Return only the scalar effective capacity κ(d, x).

        This is the main method expected to be used by the fast layer.
        """

        return self.evaluate(
            direction=direction,
            configuration=configuration,
        ).effective_capacity

    def set_base_capacity(self, value: float) -> None:
        """
        Update structural capacity c.

        The slow remodeling layer should change base capacity through this
        method rather than modifying internal fields without validation.
        """

        self.base_capacity = self._validate_non_negative_scalar(
            value,
            name="base_capacity",
        )

    def set_availability(self, value: float) -> None:
        """Update availability α while preserving the invariant 0 <= α <= 1."""

        self.availability = self._validate_unit_interval(
            value,
            name="availability",
        )

    def set_activation(self, value: float) -> None:
        """
        Update active-control coefficient.

        The value is stored for passive elements as well, but affects κ only
        when activity == ElementActivity.ACTIVE.
        """

        self.activation = self._validate_unit_interval(
            value,
            name="activation",
        )

    def copy_with(
        self,
        *,
        base_capacity: float | None = None,
        availability: float | None = None,
        activation: float | None = None,
    ) -> CapacityTensor:
        """
        Create an independent counterfactual copy.

        This method is intended for D_root sensitivity estimation and Node*
        intervention experiments, where one parameter is perturbed without
        mutating the original system.
        """

        return CapacityTensor(
            base_capacity=(
                self.base_capacity
                if base_capacity is None
                else base_capacity
            ),
            availability=(
                self.availability
                if availability is None
                else availability
            ),
            local_axis=self._axis.copy(),
            anisotropy=self._anisotropy.copy(),
            response_mode=self.response_mode,
            activity=self.activity,
            activation=(
                self.activation
                if activation is None
                else activation
            ),
            element_id=self.element_id,
        )

    @staticmethod
    def _validate_non_negative_scalar(
        value: float,
        *,
        name: str,
    ) -> float:
        result = float(value)

        if not np.isfinite(result):
            raise CapacityTensorError(
                f"{name} must be finite."
            )

        if result < 0.0:
            raise CapacityTensorError(
                f"{name} must be non-negative, received {result}."
            )

        return result

    @staticmethod
    def _validate_unit_interval(
        value: float,
        *,
        name: str,
    ) -> float:
        result = float(value)

        if not np.isfinite(result):
            raise CapacityTensorError(
                f"{name} must be finite."
            )

        if not 0.0 <= result <= 1.0:
            raise CapacityTensorError(
                f"{name} must be in [0, 1], received {result}."
            )

        return result

    @staticmethod
    def _normalize_vector(
        vector: Iterable[float] | FloatArray,
        *,
        name: str,
        expected_dimension: int | None = None,
    ) -> FloatArray:
        result = np.asarray(vector, dtype=np.float64)

        if result.ndim != 1:
            raise CapacityTensorError(
                f"{name} must be a one-dimensional vector."
            )

        if expected_dimension is not None and result.size != expected_dimension:
            raise CapacityTensorError(
                f"{name} must have dimension {expected_dimension}, "
                f"received {result.size}."
            )

        if result.size == 0:
            raise CapacityTensorError(
                f"{name} cannot be empty."
            )

        if not np.all(np.isfinite(result)):
            raise CapacityTensorError(
                f"{name} contains non-finite values."
            )

        norm = float(np.linalg.norm(result))

        if norm <= _EPSILON:
            raise CapacityTensorError(
                f"{name} cannot be a zero vector."
            )

        return result / norm

    @staticmethod
    def _validate_anisotropy_matrix(
        matrix: Iterable[Iterable[float]] | FloatArray,
        *,
        dimension: int,
    ) -> FloatArray:
        result = np.asarray(matrix, dtype=np.float64)

        expected_shape = (dimension, dimension)
        if result.shape != expected_shape:
            raise CapacityTensorError(
                "anisotropy must have shape "
                f"{expected_shape}, received {result.shape}."
            )

        if not np.all(np.isfinite(result)):
            raise CapacityTensorError(
                "anisotropy contains non-finite values."
            )

        if not np.allclose(
            result,
            result.T,
            rtol=1e-9,
            atol=1e-12,
        ):
            raise CapacityTensorError(
                "anisotropy must be symmetric."
            )

        eigenvalues = np.linalg.eigvalsh(result)

        if float(np.min(eigenvalues)) < -_EPSILON:
            raise CapacityTensorError(
                "anisotropy must be positive semidefinite."
            )

        return result.copy()


def evaluate_capacity_batch(
    capacities: Iterable[CapacityTensor],
    direction: Iterable[float] | FloatArray,
    configurations: (
        Iterable[Iterable[Iterable[float]] | FloatArray | None] | None
    ) = None,
) -> FloatArray:
    """
    Evaluate κ_i(d, x) for a sequence of elements.

    Parameters
    ----------
    capacities:
        ROIF capacity models, one per element.

    direction:
        Common external load direction.

    configurations:
        Optional orientation matrix for each element. When omitted, every
        element is evaluated in its reference configuration.

    Returns
    -------
    numpy.ndarray
        One-dimensional array of effective capacities.
    """

    capacity_list = list(capacities)

    if configurations is None:
        configuration_list = [None] * len(capacity_list)
    else:
        configuration_list = list(configurations)

        if len(configuration_list) != len(capacity_list):
            raise CapacityTensorError(
                "The number of configurations must match the number "
                "of capacity models."
            )

    return np.asarray(
        [
            capacity.kappa(
                direction=direction,
                configuration=configuration,
            )
            for capacity, configuration in zip(
                capacity_list,
                configuration_list,
                strict=True,
            )
        ],
        dtype=np.float64,
    )