from __future__ import annotations

"""
History reconstruction and hypothesis ranking for ROIF Structural Memory.

StructuralSignature answers:

    What stable imprint is currently observable?

HistoryDecoder answers:

    Which candidate causal histories are most consistent with that imprint?

This module intentionally separates four operations:

1. hypothesis construction;
2. forward simulation or reconstruction;
3. structural-signature generation;
4. hypothesis ranking.

The decoder does not invent physical laws and does not reverse time.
A candidate history must already provide a predicted StructuralSignature,
typically generated by a forward model.

The first implementation is deterministic, immutable, serializable, and
domain-independent. It supports:

- comparison with an observed StructuralSignature;
- prior plausibility;
- model-complexity penalty;
- forward-validation quality;
- configurable scoring weights;
- ranked alternatives;
- ambiguity and confidence indicators;
- explicit failure states;
- future integration with Cascade Solver, Capacity Tensor, and Viewer.
"""

from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from enum import Enum
from math import exp, isfinite
from types import MappingProxyType
from typing import Any
from uuid import uuid4

from .structural_signature import (
    SignatureComparison,
    SignatureDistanceWeights,
    StructuralSignature,
)


class HistoryDecoderError(ValueError):
    """Raised when decoding inputs or results are invalid."""


class HypothesisStatus(str, Enum):
    """Current computational status of a history hypothesis."""

    READY = "ready"
    FORWARD_VALIDATED = "forward_validated"
    INCOMPLETE = "incomplete"
    REJECTED = "rejected"
    FAILED = "failed"


class DecodeStatus(str, Enum):
    """Overall result status of one decoder run."""

    COMPLETED = "completed"
    AMBIGUOUS = "ambiguous"
    NO_CANDIDATES = "no_candidates"
    NO_VALID_CANDIDATES = "no_valid_candidates"


def _require_nonempty_string(
    value: str,
    *,
    field_name: str,
) -> str:
    if not isinstance(value, str):
        raise HistoryDecoderError(
            f"{field_name} must be a string"
        )

    normalized = value.strip()

    if not normalized:
        raise HistoryDecoderError(
            f"{field_name} must not be empty"
        )

    return normalized


def _validate_finite(
    value: float,
    *,
    field_name: str,
) -> float:
    try:
        numeric = float(value)
    except (TypeError, ValueError) as exc:
        raise HistoryDecoderError(
            f"{field_name} must be a real number"
        ) from exc

    if not isfinite(numeric):
        raise HistoryDecoderError(
            f"{field_name} must be finite"
        )

    return numeric


def _validate_nonnegative_finite(
    value: float,
    *,
    field_name: str,
) -> float:
    numeric = _validate_finite(
        value,
        field_name=field_name,
    )

    if numeric < 0.0:
        raise HistoryDecoderError(
            f"{field_name} must be non-negative"
        )

    return numeric


def _validate_unit_interval(
    value: float,
    *,
    field_name: str,
) -> float:
    numeric = _validate_nonnegative_finite(
        value,
        field_name=field_name,
    )

    if numeric > 1.0:
        raise HistoryDecoderError(
            f"{field_name} must be in [0, 1]"
        )

    return numeric


def _freeze_mapping(
    value: Mapping[str, Any] | None,
    *,
    field_name: str,
) -> Mapping[str, Any]:
    if value is None:
        return MappingProxyType({})

    if not isinstance(value, Mapping):
        raise HistoryDecoderError(
            f"{field_name} must be a mapping"
        )

    normalized: dict[str, Any] = {}

    for raw_key, item in value.items():
        key = _require_nonempty_string(
            raw_key,
            field_name=f"{field_name} key",
        )
        normalized[key] = item

    return MappingProxyType(
        dict(sorted(normalized.items()))
    )


def _normalize_ids(
    values: Iterable[str],
    *,
    field_name: str,
) -> tuple[str, ...]:
    normalized: list[str] = []
    seen: set[str] = set()

    for raw_value in values:
        value = _require_nonempty_string(
            raw_value,
            field_name=field_name,
        )

        if value in seen:
            continue

        seen.add(value)
        normalized.append(value)

    return tuple(normalized)


@dataclass(frozen=True, slots=True)
class DecoderWeights:
    """
    Weights used to rank candidate histories.

    signature_fit:
        Weight of similarity between predicted and observed signatures.

    prior:
        Weight of prior plausibility.

    validation:
        Weight of forward-validation completeness or quality.

    complexity:
        Penalty weight for unnecessarily complex hypotheses.

    custom_penalty:
        Weight of a user-defined normalized penalty.
    """

    signature_fit: float = 1.0
    prior: float = 0.25
    validation: float = 0.50
    complexity: float = 0.20
    custom_penalty: float = 0.20

    def __post_init__(self) -> None:
        for field_name in (
            "signature_fit",
            "prior",
            "validation",
            "complexity",
            "custom_penalty",
        ):
            value = _validate_nonnegative_finite(
                getattr(self, field_name),
                field_name=field_name,
            )
            object.__setattr__(
                self,
                field_name,
                value,
            )

        if self.total_positive_weight <= 0.0:
            raise HistoryDecoderError(
                "at least one positive decoder weight is required"
            )

    @property
    def total_positive_weight(self) -> float:
        return (
            self.signature_fit
            + self.prior
            + self.validation
        )

    def to_dict(self) -> dict[str, float]:
        return {
            "signature_fit": self.signature_fit,
            "prior": self.prior,
            "validation": self.validation,
            "complexity": self.complexity,
            "custom_penalty": self.custom_penalty,
        }

    @classmethod
    def from_dict(
        cls,
        data: Mapping[str, Any],
    ) -> DecoderWeights:
        if not isinstance(data, Mapping):
            raise HistoryDecoderError(
                "decoder-weight data must be a mapping"
            )

        return cls(
            signature_fit=float(
                data.get("signature_fit", 1.0)
            ),
            prior=float(
                data.get("prior", 0.25)
            ),
            validation=float(
                data.get("validation", 0.50)
            ),
            complexity=float(
                data.get("complexity", 0.20)
            ),
            custom_penalty=float(
                data.get("custom_penalty", 0.20)
            ),
        )


@dataclass(frozen=True, slots=True)
class HistoryHypothesis:
    """
    One candidate causal history.

    A hypothesis must contain a predicted StructuralSignature created by a
    forward reconstruction, analytical model, empirical template, or other
    explicit procedure.

    The decoder does not fabricate this predicted signature.
    """

    name: str
    predicted_signature: StructuralSignature

    description: str | None = None
    initiating_plane_ids: tuple[str, ...] = ()
    initiating_agent_ids: tuple[str, ...] = ()
    candidate_root_ids: tuple[str, ...] = ()

    prior_probability: float = 0.5
    validation_score: float = 1.0
    complexity: float = 0.0
    custom_penalty: float = 0.0

    status: HypothesisStatus = HypothesisStatus.READY
    metadata: Mapping[str, Any] = field(
        default_factory=dict
    )
    hypothesis_id: str = field(
        default_factory=lambda: uuid4().hex
    )

    VERSION = "1.0.0"

    def __post_init__(self) -> None:
        name = _require_nonempty_string(
            self.name,
            field_name="name",
        )
        hypothesis_id = _require_nonempty_string(
            self.hypothesis_id,
            field_name="hypothesis_id",
        )

        if not isinstance(
            self.predicted_signature,
            StructuralSignature,
        ):
            raise HistoryDecoderError(
                "predicted_signature must be a StructuralSignature"
            )

        description = self.description

        if description is not None:
            description = _require_nonempty_string(
                description,
                field_name="description",
            )

        initiating_plane_ids = _normalize_ids(
            self.initiating_plane_ids,
            field_name="initiating_plane_ids",
        )
        initiating_agent_ids = _normalize_ids(
            self.initiating_agent_ids,
            field_name="initiating_agent_ids",
        )
        candidate_root_ids = _normalize_ids(
            self.candidate_root_ids,
            field_name="candidate_root_ids",
        )

        prior_probability = _validate_unit_interval(
            self.prior_probability,
            field_name="prior_probability",
        )
        validation_score = _validate_unit_interval(
            self.validation_score,
            field_name="validation_score",
        )
        complexity = _validate_nonnegative_finite(
            self.complexity,
            field_name="complexity",
        )
        custom_penalty = _validate_unit_interval(
            self.custom_penalty,
            field_name="custom_penalty",
        )

        try:
            status = HypothesisStatus(self.status)
        except (TypeError, ValueError) as exc:
            raise HistoryDecoderError(
                f"unsupported hypothesis status: {self.status!r}"
            ) from exc

        metadata = _freeze_mapping(
            self.metadata,
            field_name="metadata",
        )

        object.__setattr__(self, "name", name)
        object.__setattr__(
            self,
            "hypothesis_id",
            hypothesis_id,
        )
        object.__setattr__(
            self,
            "description",
            description,
        )
        object.__setattr__(
            self,
            "initiating_plane_ids",
            initiating_plane_ids,
        )
        object.__setattr__(
            self,
            "initiating_agent_ids",
            initiating_agent_ids,
        )
        object.__setattr__(
            self,
            "candidate_root_ids",
            candidate_root_ids,
        )
        object.__setattr__(
            self,
            "prior_probability",
            prior_probability,
        )
        object.__setattr__(
            self,
            "validation_score",
            validation_score,
        )
        object.__setattr__(
            self,
            "complexity",
            complexity,
        )
        object.__setattr__(
            self,
            "custom_penalty",
            custom_penalty,
        )
        object.__setattr__(self, "status", status)
        object.__setattr__(
            self,
            "metadata",
            metadata,
        )

    @property
    def is_eligible(self) -> bool:
        """Return whether the hypothesis may participate in ranking."""

        return self.status in {
            HypothesisStatus.READY,
            HypothesisStatus.FORWARD_VALIDATED,
            HypothesisStatus.INCOMPLETE,
        }

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": self.VERSION,
            "hypothesis_id": self.hypothesis_id,
            "name": self.name,
            "description": self.description,
            "predicted_signature": (
                self.predicted_signature.to_dict()
            ),
            "initiating_plane_ids": list(
                self.initiating_plane_ids
            ),
            "initiating_agent_ids": list(
                self.initiating_agent_ids
            ),
            "candidate_root_ids": list(
                self.candidate_root_ids
            ),
            "prior_probability": self.prior_probability,
            "validation_score": self.validation_score,
            "complexity": self.complexity,
            "custom_penalty": self.custom_penalty,
            "status": self.status.value,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(
        cls,
        data: Mapping[str, Any],
    ) -> HistoryHypothesis:
        if not isinstance(data, Mapping):
            raise HistoryDecoderError(
                "history-hypothesis data must be a mapping"
            )

        version = data.get("version", cls.VERSION)

        if version != cls.VERSION:
            raise HistoryDecoderError(
                "unsupported history hypothesis version: "
                f"{version!r}"
            )

        signature_data = data.get(
            "predicted_signature"
        )

        if not isinstance(signature_data, Mapping):
            raise HistoryDecoderError(
                "predicted_signature is missing or invalid"
            )

        return cls(
            hypothesis_id=str(data["hypothesis_id"]),
            name=str(data["name"]),
            description=data.get("description"),
            predicted_signature=(
                StructuralSignature.from_dict(
                    signature_data
                )
            ),
            initiating_plane_ids=tuple(
                data.get("initiating_plane_ids", ())
            ),
            initiating_agent_ids=tuple(
                data.get("initiating_agent_ids", ())
            ),
            candidate_root_ids=tuple(
                data.get("candidate_root_ids", ())
            ),
            prior_probability=float(
                data.get("prior_probability", 0.5)
            ),
            validation_score=float(
                data.get("validation_score", 1.0)
            ),
            complexity=float(
                data.get("complexity", 0.0)
            ),
            custom_penalty=float(
                data.get("custom_penalty", 0.0)
            ),
            status=HypothesisStatus(
                data.get(
                    "status",
                    HypothesisStatus.READY.value,
                )
            ),
            metadata=data.get("metadata", {}),
        )


@dataclass(frozen=True, slots=True)
class HypothesisScore:
    """Scored and ranked history hypothesis."""

    hypothesis: HistoryHypothesis
    comparison: SignatureComparison

    fit_score: float
    prior_score: float
    validation_score: float
    complexity_penalty: float
    custom_penalty: float

    raw_score: float
    normalized_score: float
    rank: int = 0

    def __post_init__(self) -> None:
        if not isinstance(
            self.hypothesis,
            HistoryHypothesis,
        ):
            raise HistoryDecoderError(
                "hypothesis must be a HistoryHypothesis"
            )

        if not isinstance(
            self.comparison,
            SignatureComparison,
        ):
            raise HistoryDecoderError(
                "comparison must be a SignatureComparison"
            )

        for field_name in (
            "fit_score",
            "prior_score",
            "validation_score",
            "complexity_penalty",
            "custom_penalty",
            "normalized_score",
        ):
            value = _validate_unit_interval(
                getattr(self, field_name),
                field_name=field_name,
            )
            object.__setattr__(
                self,
                field_name,
                value,
            )

        raw_score = _validate_finite(
            self.raw_score,
            field_name="raw_score",
        )

        if not isinstance(self.rank, int):
            raise HistoryDecoderError(
                "rank must be an integer"
            )

        if self.rank < 0:
            raise HistoryDecoderError(
                "rank must be non-negative"
            )

        object.__setattr__(
            self,
            "raw_score",
            raw_score,
        )

    @property
    def hypothesis_id(self) -> str:
        return self.hypothesis.hypothesis_id

    @property
    def name(self) -> str:
        return self.hypothesis.name

    def with_rank(
        self,
        rank: int,
    ) -> HypothesisScore:
        if not isinstance(rank, int) or rank <= 0:
            raise HistoryDecoderError(
                "rank must be a positive integer"
            )

        return HypothesisScore(
            hypothesis=self.hypothesis,
            comparison=self.comparison,
            fit_score=self.fit_score,
            prior_score=self.prior_score,
            validation_score=self.validation_score,
            complexity_penalty=self.complexity_penalty,
            custom_penalty=self.custom_penalty,
            raw_score=self.raw_score,
            normalized_score=self.normalized_score,
            rank=rank,
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "hypothesis_id": self.hypothesis_id,
            "name": self.name,
            "rank": self.rank,
            "fit_score": self.fit_score,
            "prior_score": self.prior_score,
            "validation_score": self.validation_score,
            "complexity_penalty": (
                self.complexity_penalty
            ),
            "custom_penalty": self.custom_penalty,
            "raw_score": self.raw_score,
            "normalized_score": self.normalized_score,
            "comparison": self.comparison.to_dict(),
        }


@dataclass(frozen=True, slots=True)
class HistoryDecodeResult:
    """Immutable result of one inverse-history ranking run."""

    observed_signature_id: str
    status: DecodeStatus
    rankings: tuple[HypothesisScore, ...] = ()

    confidence: float = 0.0
    ambiguity: float = 1.0
    selection_margin: float = 0.0

    metadata: Mapping[str, Any] = field(
        default_factory=dict
    )
    result_id: str = field(
        default_factory=lambda: uuid4().hex
    )

    VERSION = "1.0.0"

    def __post_init__(self) -> None:
        observed_signature_id = _require_nonempty_string(
            self.observed_signature_id,
            field_name="observed_signature_id",
        )
        result_id = _require_nonempty_string(
            self.result_id,
            field_name="result_id",
        )

        try:
            status = DecodeStatus(self.status)
        except (TypeError, ValueError) as exc:
            raise HistoryDecoderError(
                f"unsupported decode status: {self.status!r}"
            ) from exc

        rankings = tuple(self.rankings)

        if not all(
            isinstance(item, HypothesisScore)
            for item in rankings
        ):
            raise HistoryDecoderError(
                "all rankings must be HypothesisScore objects"
            )

        expected_ranks = tuple(
            range(1, len(rankings) + 1)
        )
        actual_ranks = tuple(
            item.rank
            for item in rankings
        )

        if rankings and actual_ranks != expected_ranks:
            raise HistoryDecoderError(
                "ranking positions must be consecutive from one"
            )

        confidence = _validate_unit_interval(
            self.confidence,
            field_name="confidence",
        )
        ambiguity = _validate_unit_interval(
            self.ambiguity,
            field_name="ambiguity",
        )
        selection_margin = _validate_unit_interval(
            self.selection_margin,
            field_name="selection_margin",
        )

        metadata = _freeze_mapping(
            self.metadata,
            field_name="metadata",
        )

        object.__setattr__(
            self,
            "observed_signature_id",
            observed_signature_id,
        )
        object.__setattr__(self, "result_id", result_id)
        object.__setattr__(self, "status", status)
        object.__setattr__(self, "rankings", rankings)
        object.__setattr__(
            self,
            "confidence",
            confidence,
        )
        object.__setattr__(
            self,
            "ambiguity",
            ambiguity,
        )
        object.__setattr__(
            self,
            "selection_margin",
            selection_margin,
        )
        object.__setattr__(
            self,
            "metadata",
            metadata,
        )

    @property
    def best(
        self,
    ) -> HypothesisScore | None:
        return self.rankings[0] if self.rankings else None

    @property
    def alternatives(
        self,
    ) -> tuple[HypothesisScore, ...]:
        return self.rankings[1:]

    @property
    def is_ambiguous(self) -> bool:
        return self.status is DecodeStatus.AMBIGUOUS

    def top(
        self,
        count: int,
    ) -> tuple[HypothesisScore, ...]:
        if not isinstance(count, int):
            raise HistoryDecoderError(
                "count must be an integer"
            )

        if count < 0:
            raise HistoryDecoderError(
                "count must be non-negative"
            )

        return self.rankings[:count]

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": self.VERSION,
            "result_id": self.result_id,
            "observed_signature_id": (
                self.observed_signature_id
            ),
            "status": self.status.value,
            "confidence": self.confidence,
            "ambiguity": self.ambiguity,
            "selection_margin": self.selection_margin,
            "rankings": [
                item.to_dict()
                for item in self.rankings
            ],
            "metadata": dict(self.metadata),
        }


@dataclass(frozen=True, slots=True)
class HistoryDecoder:
    """
    Rank candidate histories against one observed structural signature.

    ambiguity_threshold:
        Minimum score separation required between the best and second-best
        hypotheses before the result is called non-ambiguous.

    complexity_scale:
        Converts unbounded complexity to a normalized penalty:

            complexity / (complexity + complexity_scale)
    """

    decoder_weights: DecoderWeights = field(
        default_factory=DecoderWeights
    )
    signature_weights: SignatureDistanceWeights = field(
        default_factory=SignatureDistanceWeights
    )
    ambiguity_threshold: float = 0.05
    complexity_scale: float = 5.0
    minimum_score: float = 0.0

    VERSION = "1.0.0"

    def __post_init__(self) -> None:
        if not isinstance(
            self.decoder_weights,
            DecoderWeights,
        ):
            raise HistoryDecoderError(
                "decoder_weights must be DecoderWeights"
            )

        if not isinstance(
            self.signature_weights,
            SignatureDistanceWeights,
        ):
            raise HistoryDecoderError(
                "signature_weights must be "
                "SignatureDistanceWeights"
            )

        ambiguity_threshold = _validate_unit_interval(
            self.ambiguity_threshold,
            field_name="ambiguity_threshold",
        )
        complexity_scale = _validate_nonnegative_finite(
            self.complexity_scale,
            field_name="complexity_scale",
        )

        if complexity_scale <= 0.0:
            raise HistoryDecoderError(
                "complexity_scale must be greater than zero"
            )

        minimum_score = _validate_unit_interval(
            self.minimum_score,
            field_name="minimum_score",
        )

        object.__setattr__(
            self,
            "ambiguity_threshold",
            ambiguity_threshold,
        )
        object.__setattr__(
            self,
            "complexity_scale",
            complexity_scale,
        )
        object.__setattr__(
            self,
            "minimum_score",
            minimum_score,
        )

    def _complexity_penalty(
        self,
        complexity: float,
    ) -> float:
        return complexity / (
            complexity + self.complexity_scale
        )

    def score_hypothesis(
        self,
        observed: StructuralSignature,
        hypothesis: HistoryHypothesis,
    ) -> HypothesisScore:
        """Score one candidate without assigning its final rank."""

        if not isinstance(
            observed,
            StructuralSignature,
        ):
            raise HistoryDecoderError(
                "observed must be a StructuralSignature"
            )

        if not isinstance(
            hypothesis,
            HistoryHypothesis,
        ):
            raise HistoryDecoderError(
                "hypothesis must be a HistoryHypothesis"
            )

        if not hypothesis.is_eligible:
            raise HistoryDecoderError(
                "rejected or failed hypotheses cannot be scored"
            )

        comparison = observed.compare(
            hypothesis.predicted_signature,
            weights=self.signature_weights,
        )

        fit_score = comparison.similarity
        prior_score = hypothesis.prior_probability
        validation_score = hypothesis.validation_score
        complexity_penalty = self._complexity_penalty(
            hypothesis.complexity
        )
        custom_penalty = hypothesis.custom_penalty

        positive_sum = (
            fit_score
            * self.decoder_weights.signature_fit
            + prior_score
            * self.decoder_weights.prior
            + validation_score
            * self.decoder_weights.validation
        )

        normalized_positive = (
            positive_sum
            / self.decoder_weights.total_positive_weight
        )

        total_penalty = (
            complexity_penalty
            * self.decoder_weights.complexity
            + custom_penalty
            * self.decoder_weights.custom_penalty
        )

        raw_score = (
            normalized_positive - total_penalty
        )

        normalized_score = max(
            min(raw_score, 1.0),
            0.0,
        )

        return HypothesisScore(
            hypothesis=hypothesis,
            comparison=comparison,
            fit_score=fit_score,
            prior_score=prior_score,
            validation_score=validation_score,
            complexity_penalty=complexity_penalty,
            custom_penalty=custom_penalty,
            raw_score=raw_score,
            normalized_score=normalized_score,
        )

    def decode(
        self,
        observed: StructuralSignature,
        hypotheses: Iterable[HistoryHypothesis],
        *,
        metadata: Mapping[str, Any] | None = None,
    ) -> HistoryDecodeResult:
        """Rank all eligible candidate histories."""

        if not isinstance(
            observed,
            StructuralSignature,
        ):
            raise HistoryDecoderError(
                "observed must be a StructuralSignature"
            )

        candidates = tuple(hypotheses)

        if not all(
            isinstance(item, HistoryHypothesis)
            for item in candidates
        ):
            raise HistoryDecoderError(
                "all hypotheses must be HistoryHypothesis objects"
            )

        hypothesis_ids = [
            item.hypothesis_id
            for item in candidates
        ]

        if len(hypothesis_ids) != len(
            set(hypothesis_ids)
        ):
            raise HistoryDecoderError(
                "hypothesis_id values must be unique"
            )

        if not candidates:
            return HistoryDecodeResult(
                observed_signature_id=(
                    observed.signature_id
                ),
                status=DecodeStatus.NO_CANDIDATES,
                confidence=0.0,
                ambiguity=1.0,
                selection_margin=0.0,
                metadata=metadata or {},
            )

        eligible = tuple(
            item
            for item in candidates
            if item.is_eligible
        )

        if not eligible:
            return HistoryDecodeResult(
                observed_signature_id=(
                    observed.signature_id
                ),
                status=DecodeStatus.NO_VALID_CANDIDATES,
                confidence=0.0,
                ambiguity=1.0,
                selection_margin=0.0,
                metadata=metadata or {},
            )

        scored = [
            self.score_hypothesis(
                observed,
                hypothesis,
            )
            for hypothesis in eligible
        ]

        scored.sort(
            key=lambda item: (
                -item.normalized_score,
                -item.fit_score,
                -item.validation_score,
                item.hypothesis.complexity,
                item.hypothesis_id,
            )
        )

        ranked = tuple(
            score.with_rank(index)
            for index, score in enumerate(
                scored,
                start=1,
            )
            if score.normalized_score
            >= self.minimum_score
        )

        if not ranked:
            return HistoryDecodeResult(
                observed_signature_id=(
                    observed.signature_id
                ),
                status=DecodeStatus.NO_VALID_CANDIDATES,
                confidence=0.0,
                ambiguity=1.0,
                selection_margin=0.0,
                metadata=metadata or {},
            )

        best_score = ranked[0].normalized_score

        if len(ranked) == 1:
            selection_margin = best_score
        else:
            selection_margin = max(
                best_score
                - ranked[1].normalized_score,
                0.0,
            )

        ambiguity = 1.0 - selection_margin

        confidence = (
            best_score
            * (
                0.5
                + 0.5 * selection_margin
            )
        )
        confidence = min(max(confidence, 0.0), 1.0)

        status = (
            DecodeStatus.AMBIGUOUS
            if (
                len(ranked) > 1
                and selection_margin
                < self.ambiguity_threshold
            )
            else DecodeStatus.COMPLETED
        )

        merged_metadata = {
            "decoder_version": self.VERSION,
            "candidate_count": len(candidates),
            "eligible_count": len(eligible),
            "ranked_count": len(ranked),
        }

        if metadata is not None:
            merged_metadata.update(
                dict(metadata)
            )

        return HistoryDecodeResult(
            observed_signature_id=(
                observed.signature_id
            ),
            status=status,
            rankings=ranked,
            confidence=confidence,
            ambiguity=ambiguity,
            selection_margin=selection_margin,
            metadata=merged_metadata,
        )

    def softmax_probabilities(
        self,
        result: HistoryDecodeResult,
        *,
        temperature: float = 1.0,
    ) -> Mapping[str, float]:
        """
        Convert ranked raw scores into normalized softmax probabilities.

        These are model-relative probabilities, not proof that a history is
        objectively true.
        """

        if not isinstance(
            result,
            HistoryDecodeResult,
        ):
            raise HistoryDecoderError(
                "result must be a HistoryDecodeResult"
            )

        temperature = _validate_nonnegative_finite(
            temperature,
            field_name="temperature",
        )

        if temperature <= 0.0:
            raise HistoryDecoderError(
                "temperature must be greater than zero"
            )

        if not result.rankings:
            return MappingProxyType({})

        maximum = max(
            item.raw_score
            for item in result.rankings
        )

        exponentials = {
            item.hypothesis_id: exp(
                (
                    item.raw_score - maximum
                )
                / temperature
            )
            for item in result.rankings
        }

        total = sum(exponentials.values())

        probabilities = {
            hypothesis_id: value / total
            for hypothesis_id, value
            in exponentials.items()
        }

        return MappingProxyType(
            dict(
                sorted(
                    probabilities.items()
                )
            )
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": self.VERSION,
            "decoder_weights": (
                self.decoder_weights.to_dict()
            ),
            "signature_weights": (
                self.signature_weights.to_dict()
            ),
            "ambiguity_threshold": (
                self.ambiguity_threshold
            ),
            "complexity_scale": self.complexity_scale,
            "minimum_score": self.minimum_score,
        }

    @classmethod
    def from_dict(
        cls,
        data: Mapping[str, Any],
    ) -> HistoryDecoder:
        if not isinstance(data, Mapping):
            raise HistoryDecoderError(
                "history-decoder data must be a mapping"
            )

        version = data.get("version", cls.VERSION)

        if version != cls.VERSION:
            raise HistoryDecoderError(
                "unsupported history decoder version: "
                f"{version!r}"
            )

        decoder_weights_data = data.get(
            "decoder_weights",
            {},
        )
        signature_weights_data = data.get(
            "signature_weights",
            {},
        )

        if not isinstance(
            decoder_weights_data,
            Mapping,
        ):
            raise HistoryDecoderError(
                "decoder_weights must be a mapping"
            )

        if not isinstance(
            signature_weights_data,
            Mapping,
        ):
            raise HistoryDecoderError(
                "signature_weights must be a mapping"
            )

        return cls(
            decoder_weights=DecoderWeights.from_dict(
                decoder_weights_data
            ),
            signature_weights=(
                SignatureDistanceWeights.from_dict(
                    signature_weights_data
                )
            ),
            ambiguity_threshold=float(
                data.get(
                    "ambiguity_threshold",
                    0.05,
                )
            ),
            complexity_scale=float(
                data.get(
                    "complexity_scale",
                    5.0,
                )
            ),
            minimum_score=float(
                data.get(
                    "minimum_score",
                    0.0,
                )
            ),
        )


__all__ = [
    "DecodeStatus",
    "DecoderWeights",
    "HistoryDecodeResult",
    "HistoryDecoder",
    "HistoryDecoderError",
    "HistoryHypothesis",
    "HypothesisScore",
    "HypothesisStatus",
]